name: Build and Push Docker Image

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU # particularly useful to compile/test code for r-pi by simulating systems/CPUs/devices
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Docker is a wrapper around Buildx which provides more functionality

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push multi-architecture image
        run: |
          docker buildx build \
            --platform linux/arm/v6,linux/amd64 \
            -t ghcr.io/${{ github.repository }}:latest \
            --push .
